[package]
name = "cadence_vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3"

#[[bench]]
#name = "benches"
#harness = false
#
#[dependencies]